### PR TITLE
fix camel-case capitalization of minLength and maxLength in FormInput component

### PR DESCRIPTION
**Pull request by ubergesundheit**
I noticed my tests and development versions printed out this warning when using Form.Input components:

```
Warning: Invalid DOM property `maxlength`. Did you mean `maxLength`?
          in input (created by Form.Input)
          in Form.Input (created by DropdownMenu)
          in div (created by Form.InputGroup)
         ....
```

This pull request fixes this issue by renaming `minlength` to `minLength` and `maxlength` to `maxLength` in `src/components/Form/FormInput.react.js`

I guess this is somewhat a breaking change but it makes tabler-react more correct against the official standards.

Cheers!

### CODE REVIEW

**Comment by jonthomp** [comment]
@ubergesundheit I was tempted to just release this as minor bump rather than breaking change but sticking to the rules it should be breaking as you suggest 🤷‍♂️

What do you think about keeping all 4 options so we avoid breaking?

**Comment by ubergesundheit** [comment]
Fine with me, as long as the warning is resolved. I'll see if keeping both options triggers the warning or not.

**Comment by ubergesundheit** [comment]
@jonthomp I tried your suggestion adding the correct properties instead of replacing, but this triggers the `invalid DOM property` warning.

I am fine with this being merged into a major release.

**Comment by PetrVasilev** [comment]
I'm starting to get annoyed by this error. When can you fix it?

**Comment by jonthomp** [comment]
Closing this and merging #440 instead as includes an additional fix

**Pull request closed without merging**
