### PR TITLE
fix(Form): Fix invalid properties for maxLength, minLength, autoComplete

### PR DESCRIPTION
**Pull request by akabraham**
Fix maxLength, minLength, autoComplete "Invalid DOM property" errors for Form element.

Fixes https://github.com/tabler/tabler-react/issues/434

### CODE REVIEW

**Comment by Levino** [comment]
Please merge this ASAP!

**Comment by nating** [comment]
Any chance of getting this merged and released, @AaronCoplan ? Our console would be eternally grateful! :grimacing:

**Comment by akabraham** [comment]
Who has the ability to merge this?

**Comment by blackstorm** [comment]
@akabraham I think no one. Please plan B

**Comment by Levino** [comment]
I meanwhile found that the library is badly designed overall (try to implement a logout button in the accounts dropdown). I use antd now.

**Comment by nating** [comment]
@jonthomp Any chance of a merge / release of this? 😅

**Comment by jonthomp** [comment]
Sorry all I've been away for the last 4 weeks, updates, PR merging etc incoming...

**Comment by jonthomp** [comment]
As it stands this should be a breaking change release unless we also keep the old props? Any thoughts/opinions on this?

**Comment by WoLpH** [comment]
It's indeed a breaking change but fixing it is a one-off. I would assume that the manual parameters don't get much use in any case.

It might be neater to support both but I believe it's a non-issue

**Comment by hasan-sytel** [comment]
I think we should replace with camelCase as react requires camelCase, please see similar discussion in react repo: https://github.com/facebook/react/issues/2882

**Pull request merged**
