### PR TITLE
feat(FormInput): add validation properties

### PR DESCRIPTION
**Pull request by nating**
**Changes:**

This PR adds the following validation properties to the FormInput component:
* required
* min
* max
* minlength
* maxlength

**Demonstration:**

Here is [a GIF](https://streamable.com/t3m5p) in which FormInput components are given these properties and inputs that are not valid according to these properties are shown to resolve in errors when the form is submit. 

PS. (The GIF slowed down with the compression / format conversion somewhere along the way so it's a bit slow)

### CODE REVIEW

**Comment by nating** [comment]
Hey guys, just checking in to see about this getting merged. If there's something wrong with it then no worries. I'm aware that it potentially may be *"more tabler"* to handle this stuff in Javascript.

**Comment by NickAlvesX** [comment]
Please, I need it.

**Comment by AaronCoplan** [comment]
Hello @nating @NickAlvesX  I apologize for taking so long to get to this.  I have been a bit busier than usual lately.  I am going to merge this for now, but I do agree with @nating that there might be a friendlier way to do this with Javascript as opposed to relying on html form properties.  So that may be something to explore in the future.

**Pull request merged**
