### PR TITLE
style(Tabler CSS): Add Tabler CSS, fonts and images to tabler-react

### LINKED ISSUE #159: RTL version
How can I use RTL version? there is no document nor sample.

### PR DESCRIPTION
**Pull request by jonthomp**
Brings the Tabler CSS (including RTL), fonts and images into the tabler-react src folder for distributing as part of the library.

This makes it easier to add the CSS when using tabler-react in a project and will allow us to help make sure users of our library are using the same CSS version as we expect.

The assets are copied into the dist folder as part of the prepare script before publishing to npm and can be added to a project like this:

```js
import "tabler-react/dist/Tabler.css";
```

or

```js
import "tabler-react/dist/Tabler.RTL.css";
```

Resolves #159

### CODE REVIEW

**Comment by jonthomp** [comment]
@AaronCoplan would they actually impact our JS library size or just the whole package? I thought it would only cause issue if we `import` them into our JS?

The 400+ files are all the images moving from /example to /src

**Comment by AaronCoplan** [comment]
My question is - if we merge this and then publish to npm, will anyone else who saves our library (via adding it as a dependency or just via `npm install ...`) then be downloading our images as well?  If yes, I think we should look into a different way of doing things because most people will not want to use our images as they are mostly samples - perhaps we could put them in a downloadable zip file on the demo site instead if that is the case.

**Comment by AaronCoplan** [comment]
@jonthomp Ahhh okay, thanks for the clarification - makes way more sense now - this looks good now 😂

**Pull request merged**
