### PR TITLE
Comments

### PR DESCRIPTION
**Pull request by jonthomp**
Adds components for displaying comments, lists of comments and a comments card.

### CODE REVIEW

**Comment by AaronCoplan** [comment]
@GregoryHamel I was waiting for updates to be made as per my comments.  I will check this out, rebase on top of current master, and then check the status of this code - will upload screenshots and give you a chance to review the finalized version before merging.f

**Comment by jonthomp** [comment]
@GregoryHamel @AaronCoplan thanks for picking this and all the other bits up. I've been tied up in a big project but will have some time freed up again soon hopefully!

**Comment by AaronCoplan** [comment]
@GregoryHamel Would love your review prior to merging!

**Comment by GregoryHamel** [comment]
Will do as soon as I get back tonight

**Comment by AaronCoplan** [comment]
@GregoryHamel Thanks for the quick review!

**Pull request merged**
