### PR TITLE
[WIP] Event Types

### PR DESCRIPTION
**Pull request by MrJarv1s**
Adds new Event types for use with components instead of writing types for each evenHandling type used.

A simple `import type` from the root folder with any of the following:

- AnimationEvents
- ClipboardEvents
- CompositionEvents
- FocusEvents
- FormEvents
- ImageEvents
- KeyboardEvents
- MediaEvents
- MouseEvents
- OtherEvents
- PointerEvents
- SelectionEvents
- TouchEvents
- UIEvents
- WheelEvents

Each of these will import type definition for all of their possible SyntheticEvents as defined in [ReactJS Documentation](https://reactjs.org/docs/events.html)

#199 will be resolved at the completion of this pull request.

### CODE REVIEW

**Comment by MrJarv1s** [comment]
I'm working on Form Components events, should I create a different PR once completed?

**Comment by jonthomp** [comment]
Ah yes please! Will that include events that resolve #219?

**Comment by MrJarv1s** [comment]
Yes it will, I am almost done. Just need to rework some of the account pages because they use they own event types and I am done.

**Pull request merged**
