### PR TITLE
Update FormInput.react.js

### PR DESCRIPTION
**Pull request by klip**
fix(Input): A bug fix

Added attributes "step" and "defaultValue" to input

1. Added support for passing defaultValue for an input
2. Added support for attribute "step"  for input[type=number]

image

### CODE REVIEW

**Comment by SalahAdDin** [comment]
@klip [what's about the `onClick` event](https://github.com/tabler/tabler-react/issues/531)?

**Comment by klip** [comment]
> @

Usually onClick event is not required on input. 
Currently the following events are supported and should cover 99% of all cases

    onChange,
    onMouseEnter,
    onMouseLeave,
    onPointerEnter,
    onPointerLeave,
    onFocus,
    onBlur,
    onKeyPress,
    onKeyUp,
    onKeyDown,
    onCopy,
    onCut,
    onPaste,

**Comment by SalahAdDin** [comment]
@klip It is required to `react-datetimepicker`.

**Comment by klip** [comment]
@SalahAdDin Added under the same merge request

**Review by jonthomp — APPROVED** [review]

**Pull request merged**
