### PR TITLE
Remove demo imageURL for LoginPage

### PR DESCRIPTION
**Pull request by lukeburns**
The LoginPage logo should be set by a prop. It should not be the demo logo.

### CODE REVIEW

**Comment by freddieb** [comment]
Please can this be merged soon

**Comment by lukeburns** [comment]
Updates?

**Comment by krystofbe** [comment]
I don't know why it takes such a long time to merge such a simple PR. For me tabler is dead, i'm using a paid theme now.

**Comment by Oxicode** [comment]
:o

**Review by jonthomp — APPROVED** [review]

**Comment by krystofbe** [comment]
thanks a lot @jonthomp 👍

**Pull request merged**
