### PR TITLE
fix(Dropdown): Highlight menu dropdown when underlying component selected

### PR DESCRIPTION
**Pull request by AaronCoplan**
Working to address #332

### CODE REVIEW

**Comment by ducanh2110** [comment]
validateDOMNesting(...): <li> cannot appear as a descendant of <li>.
    in li (created by ClickOutside)
    in ClickOutside (created by NavItem)
    in NavItem (created by Route)
    in Route (created by withRouter(NavItem))
    in withRouter(NavItem) (created by Nav.Link)
    in Nav.Link (created by Context.Consumer)
    in Reference (created by NavItem)
    in li (created by ClickOutside)
    in ClickOutside (created by NavItem)
    in Manager (created by NavItem)
    in NavItem (created by Nav)
    in ul (created by Nav)
    in Nav (created by Site.Nav)
    in div (created by Grid.Col)
    in Grid.Col (created by Site.Nav)
    in div (created by Grid.Row)
    in Grid.Row (created by Site.Nav)
    in div (created by Container)
    in Container (created by Site.Nav)
    in div (created by Site.Nav)
    in Site.Nav (at AppNavBar.js:100)
    in Site (at AppNavBar.js:83)
    in AppNavbar (at Home.js:22)
    in Site (at Home.js:21)
    in Home (at App.js:33)
    in Route (at App.js:41)
    in Switch (at App.js:40)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.js:39)
    in div (at App.js:38)
    in App (at src/index.js:10)
I think it still not working.

**Comment by ducanh2110** [comment]
I got this warning and when I click on the NavItem the subNavItem not showing but I check in DevTools elements the subNavItem still show/hide after click on NavItem

**Comment by AaronCoplan** [comment]
@ducanh2110 Yes, there are definitely a few things broken at the moment.  I will try to take a closer look this afternoon

**Comment by ducanh2110** [comment]
Thanks so much. Please tell me when you have done.

**Comment by AaronCoplan** [comment]
@ducanh2110 This should hopefully be fixed now - please see [this line](https://github.com/tabler/tabler-react/pull/333/files#diff-498b4ebb05bfda1d996967707f69eff1R189) for what is hopefully the only change you will have to make!  Let me know if this works for you and if so I will merge it in.

**Comment by ducanh2110** [comment]
The line in Nav.react.js right? I am using mobile and I am seeing many line. I will try later when I'm back my home. Thanks for your support. I will tell you if it work

**Comment by AaronCoplan** [comment]
No, this line `routerContextComponentType={withRouter(RouterContextProvider)}` in **SiteWrapper**.  Let me know when you get a chance to look!

**Comment by ducanh2110** [comment]
Yes. I saw that in file Nav.react.js

**Comment by AaronCoplan** [comment]
@ducanh2110 The prop is listed in both files as it is passed down through part of `tabler-react`'s internal component tree.  However, the usage you should care about / look at is in **example/src/SiteWrapper.react.js** 👍

**Comment by ducanh2110** [comment]
I understood that the file i should care is SiteWrapper. But I wanna single page app. So I need to use the others. When I am using SiteWrapper the logo is always reloading the page. And I dont want this

**Comment by ducanh2110** [comment]
Now I'm using component. Site and Site.Header Site.Nav Site.Footer instead

**Comment by AaronCoplan** [comment]
Ok, Site.Nav should work if you pass it that prop. Let me know

**Comment by AaronCoplan** [comment]
@ducanh2110 Any success?

**Comment by ducanh2110** [comment]
Sorry Aaron, I am still outside. Still not touch my computer.

**Comment by AaronCoplan** [comment]
No worries!  Just let me know when you do get the chance - hopefully I've got it fixed.

**Comment by ducanh2110** [comment]
Yes I will notice you when I test it

**Comment by ducanh2110** [comment]
I have tried it, it work correctly in example. But with my project when I'm using Site.Nav I need to use this properties:         routerContextComponentType={withRouter(RouterContextProvider)}
Is it right?. Thanks @AaronCoplan

**Comment by AaronCoplan** [comment]
@ducanh2110 Yes, what you listed `routerContextComponentType={withRouter(RouterContextProvider)}` is the correct prop!  Glad to hear it is working for you 👍

**Comment by ducanh2110** [comment]
Thanks Aaron. Please merge it in master

**Pull request merged**
