### PR TITLE
useExact for subNavItems

### PR DESCRIPTION
**Pull request by Thomas-Smyth**
https://github.com/tabler/tabler-react/issues/407

I'm not sure if this is the best solution because of the additional prop added to the `Dropdown.Item`, so feedback would be appreciated!

### CODE REVIEW

**Comment by jonthomp** [comment]
@Thomas-Smyth I think this will be fine but perhaps rename the prop to just `exact`, or at least something different to `useExact` as the impending React Hooks revolution is about to be upon us and it might mislead people.

**Comment by Thomas-Smyth** [comment]
@jonthomp would it be worth doing the same to the changes made in the previous PR regarding exact?

https://github.com/tabler/tabler-react/pull/383

**Comment by jonthomp** [comment]
I'm going to go ahead and merge this and deal with any naming issues when we get to them

**Pull request merged**
